### ISSUE TITLE
CVODES adjoint multi-threading issues?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/parPE#181]
Some problems with multi-threaded use of adjoint sensitivities have been solved in recent CVODES releases. Seems there is still one left:
```
#5  <signal handler called>
#6  0x00000000006d1ea7 in CVAdataStore (cv_mem=0x6361290, ck_mem=0x6360b90) at xxx/deps/AMICI/ThirdParty/sundials/src/cvodes/cvodea.c:2002
#7  0x00000000006cf7a6 in CVodeB (cvode_mem=0x6361290, tBout=1800, itaskB=1) at xxx/deps/AMICI/ThirdParty/sundials/src/cvodes/cvodea.c:1305
#8  0x00000000006aa2e4 in amici::CVodeSolver::solveB (this=0x612a0a0, tBout=1800, itaskB=1) at xxx/deps/AMICI/src/solver_cvodes.cpp:630
#9  0x0000000000641d26 in amici::Solver::runB (this=0x612a0a0, tout=1800) at xxx/deps/AMICI/src/solver.cpp:69
#10 0x000000000069c553 in amici::BackwardProblem::workBackwardProblem (this=0x63671f0) at xxx/deps/AMICI/src/backwardproblem.cpp:60
#11 0x000000000062729f in amici::runAmiciSimulation (solver=..., edata=0x635dbb0, model=..., rethrow=false) at xxx/deps/AMICI/src/amici.cpp:60
#12 0x00000000005e2991 in parpe::runAndLogSimulation (solverTemplate=..., model=..., conditionIdx=398, jobId=279284, dataProvider=0x2212330, resultWriter=0x22ba340, logLineSearch=false, logger=0x7fff3e9a0710) at xxx$
```
by @paulstapor

**Comment by dweindl** [comment]
Not reproducible. Closing.
